'use client'
import { useState } from 'react'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'

export default function OnboardingPage() {
  const [accepted, setAccepted] = useState(false)
  const [loading, setLoading] = useState(false)
  const router = useRouter()

  async function handleAccept() {
    if (!accepted) return
    setLoading(true)
    const supabase = createSupabaseBrowserClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (user) {
      await supabase
        .from('practitioners')
        .update({ non_diagnostic_ack_at: new Date().toISOString() })
        .eq('id', user.id)
    }
    router.push('/dashboard')
    router.refresh()
  }

  return (
    <div style={{
      minHeight: '80vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '24px',
    }}>
      <div style={{
        width: '100%',
        maxWidth: '560px',
        background: '#161618',
        border: '1px solid rgba(255,255,255,0.08)',
        borderRadius: '16px',
        padding: '32px',
      }}>
        <h1 style={{ fontSize: '1.4rem', fontWeight: 700, color: '#F5F5F5', marginBottom: '16px' }}>
          Non-Diagnostic Disclaimer
        </h1>
        <div style={{
          background: 'rgba(245,158,11,0.08)',
          border: '1px solid rgba(245,158,11,0.2)',
          borderRadius: '8px',
          padding: '16px',
          marginBottom: '24px',
          fontSize: '0.9rem',
          color: '#F5F5F5',
          lineHeight: 1.6,
        }}>
          <p style={{ marginBottom: '12px' }}>
            <strong>Posture AI is a screening tool only.</strong> It is NOT a medical diagnostic device.
          </p>
          <p style={{ marginBottom: '12px' }}>
            Results generated by this application are for informational and educational purposes only and do not constitute medical advice, diagnosis, or treatment. Posture assessments are screening indicators — they identify areas that may benefit from further professional evaluation, not diagnoses.
          </p>
          <p style={{ marginBottom: '12px' }}>
            Always use the language of screening: maintain / warning / danger and optimal / mild / moderate / significant — never normal/abnormal/diagnosis.
          </p>
          <p>
            This tool must be used by qualified movement professionals (physical therapists, fitness/movement coaches, athletic trainers, chiropractors, ergonomic coaches). Results require interpretation by a qualified professional before any corrective action is taken.
          </p>
        </div>
        <label style={{
          display: 'flex',
          alignItems: 'flex-start',
          gap: '12px',
          cursor: 'pointer',
          marginBottom: '24px',
        }}>
          <input
            type="checkbox"
            checked={accepted}
            onChange={e => setAccepted(e.target.checked)}
            style={{ marginTop: '2px', width: '16px', height: '16px', cursor: 'pointer' }}
          />
          <span style={{ fontSize: '0.875rem', color: '#A1A1AA', lineHeight: 1.5 }}>
            I understand and acknowledge that Posture AI is a screening tool, not a medical diagnostic device. I am a qualified movement professional and will use this tool appropriately.
          </span>
        </label>
        <button
          onClick={handleAccept}
          disabled={!accepted || loading}
          style={{
            width: '100%',
            padding: '12px',
            background: !accepted || loading ? 'rgba(99,102,241,0.3)' : '#6366F1',
            color: !accepted || loading ? '#A1A1AA' : '#fff',
            border: 'none',
            borderRadius: '8px',
            fontWeight: 600,
            fontSize: '0.95rem',
            cursor: !accepted || loading ? 'not-allowed' : 'pointer',
          }}
        >
          {loading ? 'Saving...' : 'I Acknowledge and Continue'}
        </button>
      </div>
    </div>
  )
}
