'use client'
import { useState } from 'react'
import { createSupabaseBrowserClient } from '@/lib/supabase/client'

export default function OnboardingPage() {
  const [accepted, setAccepted] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleAccept() {
    if (!accepted || loading) return
    setLoading(true)
    setError(null)
    const supabase = createSupabaseBrowserClient()
    const { data: { user }, error: userError } = await supabase.auth.getUser()
    if (userError || !user) {
      setError('Your session has expired. Please sign in again to continue.')
      setLoading(false)
      return
    }
    // The disclaimer ack is a compliance gate — only proceed if the write
    // is confirmed, otherwise the server gate loops the user back here.
    const { error: updateError } = await supabase
      .from('practitioners')
      .update({ non_diagnostic_ack_at: new Date().toISOString() })
      .eq('id', user.id)
    if (updateError) {
      setError('Could not save your acknowledgement. Please check your connection and try again.')
      setLoading(false)
      return
    }
    // Hard navigation: forces the server-side gate to re-read the fresh
    // ack and avoids a stale Next.js router-cache redirect back to /onboarding.
    window.location.assign('/dashboard')
  }

  return (
    <div style={{
      minHeight: '80vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '24px',
    }}>
      <div style={{
        width: '100%',
        maxWidth: '560px',
        background: 'var(--surface)',
        border: '1px solid rgba(255,255,255,0.08)',
        borderRadius: '16px',
        padding: '32px',
      }}>
        <h1 style={{ fontSize: '1.4rem', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '16px' }}>
          Non-Diagnostic Disclaimer
        </h1>
        <div style={{
          background: 'rgba(255,137,24,0.08)',
          border: '1px solid rgba(255,137,24,0.2)',
          borderRadius: '8px',
          padding: '16px',
          marginBottom: '24px',
          fontSize: '0.9rem',
          color: 'var(--text-primary)',
          lineHeight: 1.6,
        }}>
          <p style={{ marginBottom: '12px' }}>
            <strong>Posture AI is a screening tool only.</strong> It is NOT a medical diagnostic device.
          </p>
          <p style={{ marginBottom: '12px' }}>
            Results generated by this application are for informational and educational purposes only and do not constitute medical advice, diagnosis, or treatment. Posture assessments are screening indicators — they identify areas that may benefit from further professional evaluation, not diagnoses.
          </p>
          <p style={{ marginBottom: '12px' }}>
            Always use the language of screening: maintain / warning / danger and optimal / mild / moderate / significant — never normal/abnormal/diagnosis.
          </p>
          <p>
            This tool must be used by qualified movement professionals (physical therapists, fitness/movement coaches, athletic trainers, chiropractors, ergonomic coaches). Results require interpretation by a qualified professional before any corrective action is taken.
          </p>
        </div>
        <label style={{
          display: 'flex',
          alignItems: 'flex-start',
          gap: '12px',
          cursor: 'pointer',
          marginBottom: '24px',
        }}>
          <input
            type="checkbox"
            checked={accepted}
            onChange={e => setAccepted(e.target.checked)}
            style={{ marginTop: '2px', width: '16px', height: '16px', cursor: 'pointer' }}
          />
          <span style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
            I understand and acknowledge that Posture AI is a screening tool, not a medical diagnostic device. I am a qualified movement professional and will use this tool appropriately.
          </span>
        </label>
        {error && (
          <div
            role="alert"
            style={{
              background: 'rgba(239,68,68,0.12)',
              border: '1px solid rgba(239,68,68,0.3)',
              borderRadius: '8px',
              padding: '12px',
              color: 'var(--danger)',
              fontSize: '0.85rem',
              marginBottom: '16px',
            }}
          >
            {error}
          </div>
        )}
        <button
          onClick={handleAccept}
          disabled={!accepted || loading}
          style={{
            width: '100%',
            padding: '12px',
            background: !accepted || loading ? 'rgba(0,152,243,0.3)' : 'var(--brand-strong)',
            color: !accepted || loading ? 'var(--text-secondary)' : '#fff',
            border: 'none',
            borderRadius: '8px',
            fontWeight: 600,
            fontSize: '0.95rem',
            cursor: !accepted || loading ? 'not-allowed' : 'pointer',
          }}
        >
          {loading ? 'Saving...' : 'I Acknowledge and Continue'}
        </button>
      </div>
    </div>
  )
}
