// AUTO-GENERATED by scripts/generate-content-index.mjs — do not edit by hand.
import { anteriorDeltoid } from './muscles/anterior-deltoid'
import { deepAbdominals } from './muscles/deep-abdominals'
import { deepCervicalFlexors } from './muscles/deep-cervical-flexors'
import { deepHipExternalRotators } from './muscles/deep-hip-external-rotators'
import { gastrocnemiusSoleus } from './muscles/gastrocnemius-soleus'
import { gluteusMaximus } from './muscles/gluteus-maximus'
import { gluteusMedius } from './muscles/gluteus-medius'
import { hamstrings } from './muscles/hamstrings'
import { hipAdductors } from './muscles/hip-adductors'
import { iliopsoas } from './muscles/iliopsoas'
import { latissimusDorsi } from './muscles/latissimus-dorsi'
import { levatorScapulae } from './muscles/levator-scapulae'
import { lowerTrapezius } from './muscles/lower-trapezius'
import { lumbarErectorSpinae } from './muscles/lumbar-erector-spinae'
import { middleTrapezius } from './muscles/middle-trapezius'
import { obliques } from './muscles/obliques'
import { pectoralisMajor } from './muscles/pectoralis-major'
import { pectoralisMinor } from './muscles/pectoralis-minor'
import { popliteus } from './muscles/popliteus'
import { quadratusLumborum } from './muscles/quadratus-lumborum'
import { quadriceps } from './muscles/quadriceps'
import { rectusFemoris } from './muscles/rectus-femoris'
import { rhomboids } from './muscles/rhomboids'
import { serratusAnterior } from './muscles/serratus-anterior'
import { sternocleidomastoid } from './muscles/sternocleidomastoid'
import { suboccipitals } from './muscles/suboccipitals'
import { tflItBand } from './muscles/tfl-it-band'
import { thoracicErectorSpinae } from './muscles/thoracic-erector-spinae'
import { upperTrapezius } from './muscles/upper-trapezius'
import { bandPullApart } from './exercises/band-pull-apart'
import { bentKneeCalfStretch } from './exercises/bent-knee-calf-stretch'
import { birdDog } from './exercises/bird-dog'
import { butterflyStretch } from './exercises/butterfly-stretch'
import { catCow } from './exercises/cat-cow'
import { childsPoseReach } from './exercises/childs-pose-reach'
import { chinTuckHeadLift } from './exercises/chin-tuck-head-lift'
import { chinTucks } from './exercises/chin-tucks'
import { clamshell } from './exercises/clamshell'
import { deadBug } from './exercises/dead-bug'
import { doorwayPecStretch } from './exercises/doorway-pec-stretch'
import { figureFourStretch } from './exercises/figure-four-stretch'
import { foamRollLateralThigh } from './exercises/foam-roll-lateral-thigh'
import { frontPlank } from './exercises/front-plank'
import { gluteBridge } from './exercises/glute-bridge'
import { handsBehindBackChestOpener } from './exercises/hands-behind-back-chest-opener'
import { kneelingHipFlexorStretch } from './exercises/kneeling-hip-flexor-stretch'
import { kneelingLatStretch } from './exercises/kneeling-lat-stretch'
import { kneesToChestStretch } from './exercises/knees-to-chest-stretch'
import { lateralBandWalk } from './exercises/lateral-band-walk'
import { levatorScapulaeStretch } from './exercises/levator-scapulae-stretch'
import { neckLateralStretch } from './exercises/neck-lateral-stretch'
import { openBookStretch } from './exercises/open-book-stretch'
import { pallofPress } from './exercises/pallof-press'
import { proneHamstringCurl } from './exercises/prone-hamstring-curl'
import { proneHipExtension } from './exercises/prone-hip-extension'
import { proneTRaise } from './exercises/prone-t-raise'
import { proneYRaise } from './exercises/prone-y-raise'
import { pushUpPlus } from './exercises/push-up-plus'
import { seatedBandRow } from './exercises/seated-band-row'
import { seatedTibialRotation } from './exercises/seated-tibial-rotation'
import { shoulderBladeSqueeze } from './exercises/shoulder-blade-squeeze'
import { sideLungeAdductorStretch } from './exercises/side-lunge-adductor-stretch'
import { sideLyingHipAbduction } from './exercises/side-lying-hip-abduction'
import { sidePlankKnees } from './exercises/side-plank-knees'
import { sidePlank } from './exercises/side-plank'
import { singleLegBalance } from './exercises/single-leg-balance'
import { singleLegGluteBridge } from './exercises/single-leg-glute-bridge'
import { singleLegRdl } from './exercises/single-leg-rdl'
import { splitSquat } from './exercises/split-squat'
import { standingHamstringCurl } from './exercises/standing-hamstring-curl'
import { standingQlStretch } from './exercises/standing-ql-stretch'
import { standingQuadStretch } from './exercises/standing-quad-stretch'
import { standingTflStretch } from './exercises/standing-tfl-stretch'
import { sternocleidomastoidStretch } from './exercises/sternocleidomastoid-stretch'
import { suboccipitalRelease } from './exercises/suboccipital-release'
import { supineChinNod } from './exercises/supine-chin-nod'
import { supineCrossoverStretch } from './exercises/supine-crossover-stretch'
import { supinePelvicTilt } from './exercises/supine-pelvic-tilt'
import { terminalKneeExtension } from './exercises/terminal-knee-extension'
import { thoracicExtension } from './exercises/thoracic-extension'
import { wallAngels } from './exercises/wall-angels'
import { wallCalfStretch } from './exercises/wall-calf-stretch'
import { wallPushUpPlus } from './exercises/wall-push-up-plus'
import { wallSit } from './exercises/wall-sit'

import type { MuscleContent, ExerciseContent } from './muscles/types'

export const ALL_MUSCLES: MuscleContent[] = [
  anteriorDeltoid,
  deepAbdominals,
  deepCervicalFlexors,
  deepHipExternalRotators,
  gastrocnemiusSoleus,
  gluteusMaximus,
  gluteusMedius,
  hamstrings,
  hipAdductors,
  iliopsoas,
  latissimusDorsi,
  levatorScapulae,
  lowerTrapezius,
  lumbarErectorSpinae,
  middleTrapezius,
  obliques,
  pectoralisMajor,
  pectoralisMinor,
  popliteus,
  quadratusLumborum,
  quadriceps,
  rectusFemoris,
  rhomboids,
  serratusAnterior,
  sternocleidomastoid,
  suboccipitals,
  tflItBand,
  thoracicErectorSpinae,
  upperTrapezius,
]

export const ALL_EXERCISES: ExerciseContent[] = [
  bandPullApart,
  bentKneeCalfStretch,
  birdDog,
  butterflyStretch,
  catCow,
  childsPoseReach,
  chinTuckHeadLift,
  chinTucks,
  clamshell,
  deadBug,
  doorwayPecStretch,
  figureFourStretch,
  foamRollLateralThigh,
  frontPlank,
  gluteBridge,
  handsBehindBackChestOpener,
  kneelingHipFlexorStretch,
  kneelingLatStretch,
  kneesToChestStretch,
  lateralBandWalk,
  levatorScapulaeStretch,
  neckLateralStretch,
  openBookStretch,
  pallofPress,
  proneHamstringCurl,
  proneHipExtension,
  proneTRaise,
  proneYRaise,
  pushUpPlus,
  seatedBandRow,
  seatedTibialRotation,
  shoulderBladeSqueeze,
  sideLungeAdductorStretch,
  sideLyingHipAbduction,
  sidePlankKnees,
  sidePlank,
  singleLegBalance,
  singleLegGluteBridge,
  singleLegRdl,
  splitSquat,
  standingHamstringCurl,
  standingQlStretch,
  standingQuadStretch,
  standingTflStretch,
  sternocleidomastoidStretch,
  suboccipitalRelease,
  supineChinNod,
  supineCrossoverStretch,
  supinePelvicTilt,
  terminalKneeExtension,
  thoracicExtension,
  wallAngels,
  wallCalfStretch,
  wallPushUpPlus,
  wallSit,
]
