
-- SEED: imbalance_definitions
INSERT INTO imbalance_definitions (key, region, label, default_view, standard_value, unit, threshold_config, causes_text, tight_muscles, weak_muscles) VALUES
('forward_head_posture', 'head_shoulders', 'Forward Head Posture', 'side', 0, 'deg',
 '{"warning_start": 5, "danger_start": 15, "max_severity_dev": 30}'::jsonb,
 'Prolonged neck flexion (phone/desk), monitor positioned too low, loss of the normal cervical curve.',
 '["suboccipitals", "upper trapezius", "levator scapulae", "sternocleidomastoid"]'::jsonb,
 '["deep cervical flexors", "lower trapezius"]'::jsonb),
('anterior_imbalanced_shoulders', 'head_shoulders', 'Anterior Imbalanced Shoulders', 'front', 0, 'deg',
 '{"warning_start": 3, "danger_start": 8, "max_severity_dev": 20}'::jsonb,
 'Leaning the upper body to one side, carrying a bag on one side, desk work, press-dominant training.',
 '["pectoralis major", "pectoralis minor", "anterior deltoid", "upper trapezius"]'::jsonb,
 '["rhomboids", "middle trapezius", "lower trapezius", "serratus anterior"]'::jsonb),
('posterior_imbalanced_shoulders', 'head_shoulders', 'Posterior Imbalanced Shoulders', 'front', 0, 'deg',
 '{"warning_start": 3, "danger_start": 8, "max_severity_dev": 20}'::jsonb,
 'Shoulder hiking, one-sided load carrying, chronic upper-trap tension.',
 '["upper trapezius", "levator scapulae"]'::jsonb,
 '["lower trapezius"]'::jsonb),
('t1_tilt_backward', 'spine', 'T1 Tilt Backward', 'side', 0, 'deg',
 '{"warning_start": 5, "danger_start": 15, "max_severity_dev": 30}'::jsonb,
 'Repeatedly bending the spine backward, inability to stay upright when seated, poor seated support.',
 '["thoracic erector spinae", "latissimus dorsi"]'::jsonb,
 '["deep thoracic flexors", "abdominals"]'::jsonb),
('pelvic_obliquity', 'pelvis', 'Pelvic Obliquity', 'front', 0, 'deg',
 '{"warning_start": 3, "danger_start": 8, "max_severity_dev": 20}'::jsonb,
 'Crossing the legs, prolonged sedentary posture, asymmetric weight-bearing, leg-length difference.',
 '["quadratus lumborum", "adductors (elevated side)", "opposite gluteus medius"]'::jsonb,
 '["gluteus medius (elevated side)"]'::jsonb),
('anterior_pelvic_shift', 'pelvis', 'Anterior Pelvic Shift', 'side', 0, 'deg',
 '{"warning_start": 5, "danger_start": 12, "max_severity_dev": 25}'::jsonb,
 'Wearing high heels for long periods, excess abdominal weight, prolonged standing sway.',
 '["hip flexors", "lumbar erector spinae", "gastrocnemius"]'::jsonb,
 '["gluteals", "hamstrings", "abdominals"]'::jsonb),
('pelvic_axial_rotation', 'pelvis', 'Pelvic Axial Rotation', 'transverse', 0, 'deg',
 '{"warning_start": 5, "danger_start": 12, "max_severity_dev": 25}'::jsonb,
 'Crossing the legs, one-sided sports/loading, sedentary asymmetry.',
 '["one-side hip rotators", "obliques"]'::jsonb,
 '["opposite obliques", "gluteals"]'::jsonb),
('genu_varum_valgum_left', 'leg', 'Knee Alignment (Left)', 'front', 0, 'deg',
 '{"warning_start": 5, "danger_start": 12, "max_severity_dev": 25}'::jsonb,
 'Bow-legged or knock-kneed gait habits, cross-legged sitting, footwear.',
 '["tensor fasciae latae", "IT band", "lateral structures (varum) or adductors (valgum)"]'::jsonb,
 '["gluteus medius", "vastus medialis (VMO)"]'::jsonb),
('genu_varum_valgum_right', 'leg', 'Knee Alignment (Right)', 'front', 0, 'deg',
 '{"warning_start": 5, "danger_start": 12, "max_severity_dev": 25}'::jsonb,
 'Bow-legged or knock-kneed gait habits, cross-legged sitting, footwear.',
 '["tensor fasciae latae", "IT band", "lateral structures (varum) or adductors (valgum)"]'::jsonb,
 '["gluteus medius", "vastus medialis (VMO)"]'::jsonb),
('knee_extension_back_knee', 'leg', 'Knee Extension / Back Knee', 'side', 0, 'deg',
 '{"warning_start": 5, "danger_start": 12, "max_severity_dev": 25}'::jsonb,
 'Wearing high heels, joint hyperlaxity, abdominal weight shifting the center of mass backward.',
 '["quadriceps", "gastrocnemius"]'::jsonb,
 '["hamstrings", "popliteus"]'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- SEED: exercises
INSERT INTO exercises (slug, name, category, primary_deviation_keys, min_zone, instructions, sets, hold_seconds) VALUES
('chin-tucks', 'Chin Tucks', 'strengthen', ARRAY['forward_head_posture'], 'warning',
 'Stand or sit tall. Gently retract your chin straight back, making a double chin. Hold 5 seconds, then release. Repeat.', 3, 5),
('neck-lateral-stretch', 'Neck Lateral Stretch', 'stretch', ARRAY['forward_head_posture'], 'maintain',
 'Tilt your head to one side, ear toward shoulder. Gently apply light pressure with your hand. Hold 20-30 seconds. Repeat on the other side.', 3, 20),
('thoracic-extension', 'Thoracic Extension on Foam Roller', 'mobility', ARRAY['t1_tilt_backward', 'forward_head_posture'], 'warning',
 'Place a foam roller perpendicular to your spine at mid-back. Support your head with your hands. Extend back over the roller gently. Move slowly up and down the thoracic spine.', 2, 30),
('wall-angels', 'Wall Angels', 'strengthen', ARRAY['anterior_imbalanced_shoulders', 'posterior_imbalanced_shoulders'], 'maintain',
 'Stand with your back flat against a wall, arms bent at 90 degrees in contact with the wall. Slowly slide your arms up and down like making a snow angel, keeping full contact with the wall.', 3, 10),
('doorway-pec-stretch', 'Doorway Pec Stretch', 'stretch', ARRAY['anterior_imbalanced_shoulders'], 'maintain',
 'Stand in a doorway. Place your forearm on the door frame with elbow at 90 degrees. Step forward gently until you feel a stretch across your chest. Hold 20-30 seconds. Repeat both sides.', 3, 20),
('kneeling-hip-flexor-stretch', 'Kneeling Hip Flexor Stretch', 'stretch', ARRAY['anterior_pelvic_shift', 'pelvic_obliquity'], 'warning',
 'Kneel with one knee on the ground and the other foot forward (lunge position). Shift your hips forward until you feel a stretch in the front of the hip. Keep your back straight. Hold 20-30 seconds. Repeat both sides.', 3, 20),
('glute-bridge', 'Glute Bridge', 'strengthen', ARRAY['anterior_pelvic_shift', 'knee_extension_back_knee'], 'maintain',
 'Lie on your back with knees bent and feet flat on the floor. Squeeze your glutes and drive your hips up until your body forms a straight line from knees to shoulders. Hold 2 seconds at the top. Lower slowly.', 3, 2),
('clamshell', 'Clamshell Exercise', 'strengthen', ARRAY['pelvic_obliquity', 'genu_varum_valgum_left', 'genu_varum_valgum_right'], 'warning',
 'Lie on your side with knees stacked and bent at 45 degrees. Keeping your feet together, open your top knee upward like a clamshell. Pause, then lower slowly. Repeat on both sides.', 3, 5),
('single-leg-balance', 'Single Leg Balance', 'activation', ARRAY['pelvic_obliquity', 'genu_varum_valgum_left', 'genu_varum_valgum_right'], 'warning',
 'Stand on one foot with a slight bend in the knee. Maintain your balance for 30 seconds. Keep your hips level. Progress to eyes closed for added challenge. Repeat on both sides.', 3, 30),
('standing-hamstring-curl', 'Standing Hamstring Curl', 'strengthen', ARRAY['knee_extension_back_knee'], 'warning',
 'Stand holding a wall or chair for balance. Slowly curl one heel up toward your glutes against gravity. Hold briefly at the top, then lower with control. Keep your thighs parallel.', 3, 5)
ON CONFLICT (slug) DO NOTHING;
